### PR TITLE
RD-1247 Put help icon after the required indicator

### PR DESCRIPTION
**Pull request by leon-good-life**
## Description
[Jira ticket: RD-1247
](https://cloudifysource.atlassian.net/browse/RD-1247)

## Screenshots / Videos

Screen Shot 2022-05-11 at 17 20 35

Screen Shot 2022-05-15 at 12 35 09

## Checklist

- [x] My code follows the [UI Code Style](https://cloudifysource.atlassian.net/l/c/x8fq902p).
- [x] I verified that all tests and checks have passed.
- [ ] I verified if that change requires any update in the [documentation](https://cloudifysource.atlassian.net/l/c/4XKtPocy).
- [x] I added proper labels to this PR.

## Tests
I wrote a story. screenshot above.

I ran `npm pack` on this branch and I installed on Cloudify-stage.

I tested it in Cloudify-stage.

 

## Documentation
The screenshots in docs repo will be updated when I will update version in Stage.
I need to make PR in docs repo.

### CODE REVIEW

**Review by qooban — COMMENTED** [review]
Code looks fine. Please update tests and verify in Stage.

**Comment by leon-good-life** [comment]
I tested it on Cloudify-Stage. I added a screenshot to the PR description.

**Comment by leon-good-life** [comment]
display-block causing a bug, I need to change that

**Comment by leon-good-life** [comment]
I fixed, here are the screenshots:
Screen Shot 2022-05-24 at 9 23 09
The bug that was before doesn't occur:
Screen Shot 2022-05-24 at 9 25 16

**Comment by leon-good-life** [comment]
@qooban I forgot how to update Loki screenshots

**Comment by leon-good-life** [comment]
All checks have passed

**Review by qooban — APPROVED** [review]

**Pull request merged**
