### PR TITLE
RD-5709 Rename all files to have .ts or .tsx extension - part 1 `src` folder

### PR DESCRIPTION
**Pull request by PatrycjaKubiczek**
## Description

RD-5709 
- rename files from .js and .jsx to .ts and .tsx
- add ts-expected-error to files that are not fully migrated
- added export to some interfaces to fix issues with CI

**Notes:**
This is part 1 or renaming all files from Components repo, it contains renamed files from `src` folder. Because this PR has already  135 files I decided to split the work into smaller PR's. 

I used the [ts-migrate](https://github.com/airbnb/ts-migrate) tool to rename and add `ts-expected-error`'s  as comments, thanks to this approach we will have a couple of benefits:
- we won't ignore all errors, so we won't have problems similar to stage and composer with `ts-nocheck`
- we could easily find similar issues/errors
- we can easily estimate how much effort it would take to migrate specific files.

However, there are some flaws as well:
- we would need to adjust the script which counts our TS migration progress: https://github.com/cloudify-cosmo/cloudify-ui-common/blob/master/scripts/get-ts-migration-progress.sh - PR https://github.com/cloudify-cosmo/cloudify-ui-common/pull/135
- files became a bit bulky ;) 

In overall I think we gain much more than we lose, so IMO it's a good approach. 

## Screenshots / Videos

n/a 

## Checklist

- [x] My code follows the [UI Code Style](https://cloudifysource.atlassian.net/l/c/x8fq902p).
- [x] I verified that all tests and checks have passed.
- [x] I verified if that change requires any update in the [documentation](https://cloudifysource.atlassian.net/l/c/4XKtPocy).
- [x] I added proper labels to this PR.

## Tests

 

CI checks are green 💹

## Documentation

I will update README after finishing the migration.

### CODE REVIEW

**Comment by Vorbert-Kruk** [comment]
Also will review on Monday 😁

**Comment by PatrycjaKubiczek** [comment]
> Will review properly on Monday.
> 
> In general - I like the direction 👍🏻 I suspect that the second part will consists of `test` folder, am I correct?
> 
> If renaming internal files (`.jest` and `.storybook` folders) will require big effort, we can wait and do it at once within closing task - [RD-5749](https://cloudifysource.atlassian.net/browse/RD-5749).

@qooban yes, that's the plan

**Review by Vorbert-Kruk — APPROVED** [review]
LGTM 🎉

**Review by qooban — APPROVED** [review]
Looks good! 👍🏻 

Got just 2 general comments:

1. I see you added `export` to props interfaces, that's great, we should do that. Are there any missing? If so, let's just add a guideline in the epic so others will not forget about it, OK?
2. Regarding stories I think it would be nice to type the stories properly (see eg. `GenericField.stories.tsx` - there's such type: `Story<Required<GenericFieldProps>>` used for stories typing). As we have right now all stories in `.tsx` it will be easy to forget about it, so can we have that in the guidelines as well?

**Comment by PatrycjaKubiczek** [comment]
@qooban I added additional points in the ticket's description: https://cloudifysource.atlassian.net/browse/RD-5590

**Pull request merged**
